from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd

from utils.io import write_csv, write_json


def export_bundle(output_dir: Path, run_metadata: dict[str, Any], summary_metrics: dict[str, Any], trades: pd.DataFrame, signals: pd.DataFrame, daily_equity: pd.DataFrame, ablation: pd.DataFrame, grid: pd.DataFrame, walkforward: pd.DataFrame, report_relpath: str = "reports/report.md") -> dict[str, Any]:
    output_dir.mkdir(parents=True, exist_ok=True)
    write_json(output_dir / "run_metadata.json", run_metadata)
    write_json(output_dir / "summary_metrics.json", summary_metrics)
    write_csv(output_dir / "trades.csv", trades)
    write_csv(output_dir / "signals.csv", signals)
    write_csv(output_dir / "daily_equity.csv", daily_equity)
    write_csv(output_dir / "ablation_results.csv", ablation)
    write_csv(output_dir / "parameter_grid_results.csv", grid)
    write_csv(output_dir / "walkforward_results.csv", walkforward)
    return {
        "run": {
            "runId": run_metadata.get("run_id"),
            "strategyVersion": run_metadata.get("strategy_version"),
            "dateRange": f"{run_metadata.get('start_date')} to {run_metadata.get('end_date')}",
            "universe": run_metadata.get("universe_name"),
            "benchmark": run_metadata.get("benchmark_symbol"),
            "status": "completed",
            "generatedAt": pd.Timestamp.utcnow().isoformat(),
        },
        "metrics": {
            "totalTrades": summary_metrics.get("totalTrades"),
            "winRate": summary_metrics.get("winRate"),
            "profitFactor": summary_metrics.get("profitFactor"),
            "expectancy": summary_metrics.get("expectancy"),
            "cagr": summary_metrics.get("cagr"),
            "sharpe": summary_metrics.get("sharpe"),
            "maxDrawdown": summary_metrics.get("maxDrawdown"),
            "exposure": summary_metrics.get("exposure"),
            "averageHoldTime": f"{summary_metrics.get('averageHoldTime', 0):.1f} trading days",
        },
        "files": [
            {"name": "summary_metrics.json", "path": str((output_dir / "summary_metrics.json").as_posix()), "kind": "json"},
            {"name": "run_metadata.json", "path": str((output_dir / "run_metadata.json").as_posix()), "kind": "json"},
            {"name": "trades.csv", "path": str((output_dir / "trades.csv").as_posix()), "kind": "csv"},
            {"name": "signals.csv", "path": str((output_dir / "signals.csv").as_posix()), "kind": "csv"},
            {"name": "daily_equity.csv", "path": str((output_dir / "daily_equity.csv").as_posix()), "kind": "csv"},
            {"name": "ablation_results.csv", "path": str((output_dir / "ablation_results.csv").as_posix()), "kind": "csv"},
            {"name": "parameter_grid_results.csv", "path": str((output_dir / "parameter_grid_results.csv").as_posix()), "kind": "csv"},
            {"name": "walkforward_results.csv", "path": str((output_dir / "walkforward_results.csv").as_posix()), "kind": "csv"},
            {"name": "report.md", "path": str((output_dir / report_relpath).as_posix()), "kind": "markdown"},
        ],
        "chartImages": [],
        "notes": ["Generated by isolated wsp_backtest engine", "File-based artifact contract for Module 1"],
        "source": "artifact-loader",
    }
