
CREATE OR REPLACE FUNCTION public.display_industry(raw_industry text)
 RETURNS text
 LANGUAGE sql
 IMMUTABLE
 SET search_path TO 'public'
AS $function$
  SELECT CASE
    -- Excluded / non-equity
    WHEN raw_industry ILIKE '%Stocks Proxy Basket%' THEN 'ETF'
    WHEN raw_industry ILIKE '%Exchange Traded Fund%' THEN 'ETF'

    -- Technology
    WHEN raw_industry ILIKE '%SEMICONDUCTOR%' THEN 'Semiconductors'
    WHEN raw_industry ILIKE '%PRINTED CIRCUIT%' THEN 'Semiconductors'
    WHEN raw_industry ILIKE '%ELECTRONIC COMPONENT%' THEN 'Electronic Components'
    WHEN raw_industry ILIKE '%ELECTRONIC CONNECTOR%' THEN 'Electronic Components'
    WHEN raw_industry ILIKE '%ELECTRONIC COIL%' THEN 'Electronic Components'
    WHEN raw_industry ILIKE '%SWITCHGEAR%' THEN 'Electronic Components'
    WHEN raw_industry ILIKE '%COMPUTER COMMUNICATIONS%' THEN 'Networking Equipment'
    WHEN raw_industry ILIKE '%COMMUNICATIONS EQUIPMENT%' THEN 'Communications Equipment'
    WHEN raw_industry ILIKE '%COMPUTER PERIPHERAL%' THEN 'Computer Hardware'
    WHEN raw_industry ILIKE '%COMPUTER & OFFICE%' THEN 'Computer Hardware'
    WHEN raw_industry ILIKE '%CALCULATING%' THEN 'Computer Hardware'
    WHEN raw_industry ILIKE '%ELECTRONIC%COMPUTER%' THEN 'Computer Hardware'
    WHEN raw_industry ILIKE '%COMPUTER STORAGE%' THEN 'Computer Hardware'
    WHEN raw_industry ILIKE '%PREPACKAGED SOFTWARE%' THEN 'Software'
    WHEN raw_industry ILIKE '%SOFTWARE%' THEN 'Software'
    WHEN raw_industry ILIKE '%INFORMATION RETRIEVAL%' THEN 'IT Services'
    WHEN raw_industry ILIKE '%COMPUTER PROCESSING%' THEN 'IT Services'
    WHEN raw_industry ILIKE '%COMPUTER INTEGRATED%' THEN 'IT Services'
    WHEN raw_industry ILIKE '%COMPUTER PROGRAMMING%' AND raw_industry NOT ILIKE '%DATA PROC%' THEN 'IT Services'
    WHEN raw_industry ILIKE '%COMPUTER RENTAL%' THEN 'IT Services'
    WHEN raw_industry ILIKE 'Information Technology%' THEN 'IT Services'
    WHEN raw_industry ILIKE '%PATENT OWNERS%' THEN 'IT Services'
    WHEN raw_industry ILIKE '%OPTICAL INSTRUMENT%' THEN 'Scientific Instruments'
    WHEN raw_industry ILIKE '%MEASURING%CONTROLLING%' THEN 'Scientific Instruments'
    WHEN raw_industry ILIKE '%LABORATORY%INSTRUMENT%' THEN 'Scientific Instruments'
    WHEN raw_industry ILIKE '%TOTALIZING FLUID%' THEN 'Scientific Instruments'
    WHEN raw_industry ILIKE '%INSTRUMENTS FOR MEAS%' THEN 'Scientific Instruments'
    WHEN raw_industry ILIKE '%SEARCH, DETECTION%' THEN 'Defense Electronics'
    WHEN raw_industry ILIKE '%Search Detection%' THEN 'Defense Electronics'
    WHEN raw_industry ILIKE '%PHOTOGRAPHIC EQUIPMENT%' THEN 'Scientific Instruments'
    WHEN raw_industry ILIKE '%Photographic Equipment%' THEN 'Scientific Instruments'
    WHEN raw_industry ILIKE '%X-RAY APPARATUS%' THEN 'Medical Devices'
    
    -- Healthcare
    WHEN raw_industry ILIKE '%PHARMACEUTICAL%' THEN 'Pharmaceuticals'
    WHEN raw_industry ILIKE '%Drug Manufacturer%' THEN 'Pharmaceuticals'
    WHEN raw_industry ILIKE '%BIOLOGICAL PRODUCT%' THEN 'Biotechnology'
    WHEN raw_industry ILIKE '%Biotechnology%' THEN 'Biotechnology'
    WHEN raw_industry ILIKE '%IN VITRO%' THEN 'Diagnostics'
    WHEN raw_industry ILIKE '%SURGICAL & MEDICAL%' THEN 'Medical Devices'
    WHEN raw_industry ILIKE '%SURGICAL%MEDICAL%INSTRUMENT%' THEN 'Medical Devices'
    WHEN raw_industry ILIKE '%ELECTROMEDICAL%' THEN 'Medical Devices'
    WHEN raw_industry ILIKE '%Medical Device%' THEN 'Medical Devices'
    WHEN raw_industry ILIKE '%Medical Instrument%' THEN 'Medical Devices'
    WHEN raw_industry ILIKE '%DENTAL EQUIPMENT%' THEN 'Medical Devices'
    WHEN raw_industry ILIKE '%ORTHOPEDIC%' THEN 'Medical Devices'
    WHEN raw_industry ILIKE '%OPHTHALMIC%' THEN 'Medical Devices'
    WHEN raw_industry ILIKE '%HOSPITAL%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%HEALTH SERVICES%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%SERVICES-HEALTH%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%HOME HEALTH CARE%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%MEDICAL LABORATORIES%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%Health Care%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%Managed Health%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%OFFICES%CLINICS%DOCTOR%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%Offices Clinics%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%MISC HEALTH%' THEN 'Healthcare Services'
    WHEN raw_industry ILIKE '%Wholesale%Drug%' THEN 'Distribution'
    
    -- Financials
    WHEN raw_industry ILIKE '%NATIONAL COMMERCIAL BANK%' THEN 'Banks'
    WHEN raw_industry ILIKE '%STATE COMMERCIAL BANK%' THEN 'Banks'
    WHEN raw_industry ILIKE '%COMMERCIAL BANKS%' THEN 'Banks'
    WHEN raw_industry ILIKE '%SAVINGS INSTITUTION%' THEN 'Banks'
    WHEN raw_industry = 'Banks' THEN 'Banks'
    WHEN raw_industry ILIKE '%FUNCTIONS RELATED TO DEPOSITORY%' THEN 'Banks'
    WHEN raw_industry ILIKE '%INSURANCE AGENT%' THEN 'Insurance'
    WHEN raw_industry ILIKE '%FIRE, MARINE%' THEN 'Insurance'
    WHEN raw_industry ILIKE '%LIFE INSURANCE%' THEN 'Insurance'
    WHEN raw_industry ILIKE '%ACCIDENT & HEALTH%' THEN 'Insurance'
    WHEN raw_industry ILIKE '%SURETY INSURANCE%' THEN 'Insurance'
    WHEN raw_industry ILIKE '%Insurance%' THEN 'Insurance'
    WHEN raw_industry ILIKE '%SECURITY & COMMODITY%' THEN 'Capital Markets'
    WHEN raw_industry ILIKE '%SECURITY BROKERS%' THEN 'Capital Markets'
    WHEN raw_industry ILIKE '%Security Brokers%' THEN 'Capital Markets'
    WHEN raw_industry ILIKE '%Security Commodity%' THEN 'Capital Markets'
    WHEN raw_industry ILIKE '%INVESTMENT ADVICE%' THEN 'Capital Markets'
    WHEN raw_industry ILIKE '%COMMODITY CONTRACT%' THEN 'Capital Markets'
    WHEN raw_industry ILIKE '%Capital Markets%' THEN 'Capital Markets'
    WHEN raw_industry ILIKE '%INVESTORS%NEC%' THEN 'Capital Markets'
    WHEN raw_industry ILIKE '%FINANCE SERVICES%' THEN 'Financial Services'
    WHEN raw_industry ILIKE '%Financial Data%' THEN 'Financial Services'
    WHEN raw_industry ILIKE '%SHORT-TERM BUSINESS CREDIT%' THEN 'Financial Services'
    WHEN raw_industry ILIKE '%ASSET-BACKED%' THEN 'Financial Services'
    WHEN raw_industry ILIKE '%PERSONAL CREDIT%' THEN 'Consumer Finance'
    WHEN raw_industry ILIKE '%LOAN BROKERS%' THEN 'Consumer Finance'
    WHEN raw_industry ILIKE '%Consumer Credit%' THEN 'Consumer Finance'
    WHEN raw_industry ILIKE '%MORTGAGE BANK%' THEN 'Mortgage Finance'
    WHEN raw_industry ILIKE '%REAL ESTATE INVESTMENT%' THEN 'REITs'
    WHEN raw_industry ILIKE '%REIT%' THEN 'REITs'
    WHEN raw_industry ILIKE '%BLANK CHECK%' THEN 'SPACs'
    WHEN raw_industry ILIKE '%Payment Service%' THEN 'Payment Services'
    
    -- Energy
    WHEN raw_industry ILIKE '%CRUDE PETROLEUM%' THEN 'Oil & Gas E&P'
    WHEN raw_industry ILIKE '%Oil & Gas E&P%' THEN 'Oil & Gas E&P'
    WHEN raw_industry ILIKE '%DRILLING OIL%' THEN 'Oil & Gas Services'
    WHEN raw_industry ILIKE '%OIL & GAS FIELD%' THEN 'Oil & Gas Services'
    WHEN raw_industry ILIKE '%Oil Gas Field%' THEN 'Oil & Gas Services'
    WHEN raw_industry ILIKE '%Oil & Gas Equipment%' THEN 'Oil & Gas Services'
    WHEN raw_industry ILIKE '%OIL ROYALTY%' THEN 'Oil & Gas E&P'
    WHEN raw_industry ILIKE '%PETROLEUM REFINING%' THEN 'Oil & Gas Refining'
    WHEN raw_industry ILIKE '%Integrated Oil%' THEN 'Integrated Oil & Gas'
    WHEN raw_industry ILIKE '%NATURAL GAS DISTRIBUTION%' THEN 'Natural Gas'
    WHEN raw_industry ILIKE '%NATURAL GAS TRANSMIS%' THEN 'Natural Gas'
    WHEN raw_industry ILIKE '%PIPELINE%' THEN 'Pipelines'
    WHEN raw_industry ILIKE '%PIPE LINE%' THEN 'Pipelines'
    WHEN raw_industry ILIKE '%Pipe Lines%' THEN 'Pipelines'
    WHEN raw_industry ILIKE '%Oil & Gas Midstream%' THEN 'Pipelines'
    WHEN raw_industry ILIKE '%COAL%' THEN 'Coal & Consumable Fuels'
    
    -- Industrials
    WHEN raw_industry ILIKE '%AIRCRAFT%' THEN 'Aerospace & Defense'
    WHEN raw_industry ILIKE '%Aerospace%' THEN 'Aerospace & Defense'
    WHEN raw_industry ILIKE '%GUIDED MISSILE%' THEN 'Aerospace & Defense'
    WHEN raw_industry ILIKE '%SHIP & BOAT%' THEN 'Aerospace & Defense'
    WHEN raw_industry ILIKE '%Ship Boat%' THEN 'Aerospace & Defense'
    WHEN raw_industry ILIKE '%RAILROAD%' THEN 'Railroads'
    WHEN raw_industry ILIKE '%TRUCKING%' THEN 'Trucking'
    WHEN raw_industry ILIKE '%TRUCK%BUS%BOD%' THEN 'Trucking'
    WHEN raw_industry ILIKE '%Truck%Bus%Bod%' THEN 'Trucking'
    WHEN raw_industry ILIKE '%AIR TRANSPORTATION%' THEN 'Airlines'
    WHEN raw_industry ILIKE '%Air Transportation%' THEN 'Airlines'
    WHEN raw_industry ILIKE '%AIR COURIER%' THEN 'Air Freight'
    WHEN raw_industry ILIKE '%ARRANGEMENT OF TRANSPORT%' THEN 'Logistics'
    WHEN raw_industry ILIKE '%Arrangement Of Transport%' THEN 'Logistics'
    WHEN raw_industry ILIKE '%Integrated Freight%' THEN 'Logistics'
    WHEN raw_industry ILIKE '%DEEP SEA%' THEN 'Marine Transportation'
    WHEN raw_industry ILIKE '%WATER TRANSPORTATION%' THEN 'Marine Transportation'
    WHEN raw_industry ILIKE '%Water Transportation%' THEN 'Marine Transportation'
    WHEN raw_industry ILIKE '%TRANSPORTATION SERVICE%' THEN 'Logistics'
    WHEN raw_industry ILIKE '%Transportation Service%' THEN 'Logistics'
    WHEN raw_industry ILIKE '%Travel Service%' THEN 'Logistics'
    WHEN raw_industry ILIKE '%PUBLIC WAREHOUSING%' THEN 'Logistics'
    WHEN raw_industry ILIKE '%CONSTRUCTION MACHINERY%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%CONSTRUCTION, MINING%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%FARM MACHINERY%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%GENERAL INDUSTRIAL MACHINERY%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%SPECIAL INDUSTRY MACHINERY%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%METALWORKG MACHINERY%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%ENGINES & TURBINES%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%PUMPS%PUMPING%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%Pumps%Pumping%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%INDUSTRIAL%FANS%BLOWER%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%INDUSTRIAL TRUCK%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%MACHINE TOOL%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%Machinery%' THEN 'Machinery'
    WHEN raw_industry ILIKE '%MOTORS & GENERATORS%' THEN 'Electrical Equipment'
    WHEN raw_industry ILIKE '%GENERAL BLDG CONTRACTOR%' THEN 'Construction'
    WHEN raw_industry ILIKE '%HEAVY CONSTRUCTION%' THEN 'Construction'
    WHEN raw_industry ILIKE '%CONSTRUCTION - SPECIAL%' THEN 'Construction'
    WHEN raw_industry ILIKE '%Construction Special%' THEN 'Construction'
    WHEN raw_industry ILIKE '%ELECTRICAL WORK%' THEN 'Construction'
    WHEN raw_industry ILIKE '%ELECTRIC LIGHTING%' THEN 'Electrical Equipment'
    WHEN raw_industry ILIKE '%ELECTRIC HOUSEWARES%' THEN 'Electrical Equipment'
    WHEN raw_industry ILIKE '%Electrical Equipment%' THEN 'Electrical Equipment'
    WHEN raw_industry ILIKE '%MISCELLANEOUS ELECTRICAL%' THEN 'Electrical Equipment'
    WHEN raw_industry ILIKE '%Miscellaneous Electrical%' THEN 'Electrical Equipment'
    WHEN raw_industry ILIKE '%INDUSTRIAL INSTRUMENTS%' THEN 'Industrial Technology'
    WHEN raw_industry ILIKE '%PROCESS CONTROL%' THEN 'Industrial Technology'
    WHEN raw_industry ILIKE '%SERVICES-MANAGEMENT CONSULTING%' THEN 'Professional Services'
    WHEN raw_industry ILIKE '%Services Management Consulting%' THEN 'Professional Services'
    WHEN raw_industry ILIKE '%SERVICES-ENGINEERING%' THEN 'Professional Services'
    WHEN raw_industry ILIKE '%Services Engineering%' THEN 'Professional Services'
    WHEN raw_industry ILIKE '%SERVICES-MISC BUSINESS%' THEN 'Professional Services'
    WHEN raw_industry ILIKE '%SERVICES-HELP SUPPLY%' THEN 'Staffing'
    WHEN raw_industry ILIKE '%Services Help Supply%' THEN 'Staffing'
    WHEN raw_industry ILIKE '%Services Employment%' THEN 'Staffing'
    WHEN raw_industry ILIKE '%Staffing%' THEN 'Staffing'
    WHEN raw_industry ILIKE '%SERVICES-TO BUILDINGS%' THEN 'Facility Services'
    WHEN raw_industry ILIKE '%Waste Management%' THEN 'Waste Management'
    WHEN raw_industry ILIKE '%REFUSE SYSTEMS%' THEN 'Waste Management'
    WHEN raw_industry ILIKE '%Conglomerate%' THEN 'Conglomerates'
    WHEN raw_industry ILIKE '%HEATING EQUIP%' THEN 'HVAC'
    WHEN raw_industry ILIKE '%Heating Equip%' THEN 'HVAC'
    WHEN raw_industry ILIKE '%AIR-COND%WARM AIR%' THEN 'HVAC'
    WHEN raw_industry ILIKE '%Air Cond%Warm Air%' THEN 'HVAC'
    WHEN raw_industry ILIKE '%Auto Rental%' THEN 'Business Services'
    WHEN raw_industry ILIKE '%Automotive Repair%' THEN 'Business Services'
    WHEN raw_industry ILIKE '%Miscellaneous Equipment Rental%' THEN 'Business Services'
    
    -- Materials
    WHEN raw_industry ILIKE '%STEEL%' THEN 'Steel'
    WHEN raw_industry ILIKE '%IRON ORES%' THEN 'Steel'
    WHEN raw_industry ILIKE '%ALUMINUM%' THEN 'Aluminum'
    WHEN raw_industry ILIKE '%GOLD%' THEN 'Gold'
    WHEN raw_industry ILIKE '%Gold Miner%' THEN 'Gold'
    WHEN raw_industry ILIKE '%Copper%' THEN 'Copper'
    WHEN raw_industry ILIKE '%METAL MINING%' THEN 'Mining'
    WHEN raw_industry ILIKE '%MINING%QUARRYING%' THEN 'Mining'
    WHEN raw_industry ILIKE '%SECONDARY SMELTING%' THEN 'Metals & Mining'
    WHEN raw_industry ILIKE '%ROLLING DRAWING%EXTRUDING%' THEN 'Metals & Mining'
    WHEN raw_industry ILIKE '%Rolling Drawing%Extruding%' THEN 'Metals & Mining'
    WHEN raw_industry ILIKE '%NONFERROUS FOUNDRI%' THEN 'Metals & Mining'
    WHEN raw_industry ILIKE '%Nonferrous Foundri%' THEN 'Metals & Mining'
    WHEN raw_industry ILIKE '%DRAWING%INSULATING%NONFERROUS%' THEN 'Metals & Mining'
    WHEN raw_industry ILIKE '%Drawing%Insulating%Nonferrous%' THEN 'Metals & Mining'
    WHEN raw_industry ILIKE '%MISCELLANEOUS PRIMARY METAL%' THEN 'Metals & Mining'
    WHEN raw_industry ILIKE '%CHEMICALS%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%Specialty Chemical%' THEN 'Specialty Chemicals'
    WHEN raw_industry ILIKE '%MISCELLANEOUS CHEMICAL%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%Miscellaneous Chemical%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%AGRICULTURAL CHEMICAL%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%INDUSTRIAL ORGANIC CHEMICAL%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%INDUSTRIAL INORGANIC CHEMICAL%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%PLASTIC MATERIAL%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%PLASTICS PRODUCT%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%Plastics Product%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%Miscellaneous Plastics%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%SOAP%DETERGENT%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%SPECIALTY CLEANING%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%ADHESIVE%SEALANT%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%Adhesive%Sealant%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%PAINTS%VARNISH%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%Paints%Varnish%' THEN 'Chemicals'
    WHEN raw_industry ILIKE '%PERFUME%' THEN 'Household Products'
    WHEN raw_industry ILIKE '%Household%' THEN 'Household Products'
    WHEN raw_industry ILIKE '%CEMENT%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%GLASS PRODUCT%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%Glass Container%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%LUMBER%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%CONCRETE%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%ABRASIVE%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%Abrasive%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%MILLWOOD%VENEER%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%Millwood%Veneer%' THEN 'Building Materials'
    WHEN raw_industry ILIKE '%PAPER MILL%' THEN 'Paper & Packaging'
    WHEN raw_industry ILIKE '%PAPERBOARD%' THEN 'Paper & Packaging'
    WHEN raw_industry ILIKE '%CONVERTED PAPER%' THEN 'Paper & Packaging'
    WHEN raw_industry ILIKE '%Pulp Mill%' THEN 'Paper & Packaging'
    WHEN raw_industry ILIKE '%METAL CAN%' THEN 'Packaging'
    WHEN raw_industry ILIKE '%Metal Shipping%' THEN 'Packaging'
    WHEN raw_industry ILIKE '%FABRICATED PLATE%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%FABRICATED STRUCTURAL%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%FABRICATED RUBBER%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%MISCELLANEOUS FABRICATED METAL%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%METAL DOORS%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%Metal Doors%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%METAL FORGING%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%CUTLERY%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%DRAWING & INSULATING%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%GASKET%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%Gasket%' THEN 'Fabricated Metals'
    WHEN raw_industry ILIKE '%TIRES%INNER TUBES%' THEN 'Auto Parts'
    WHEN raw_industry ILIKE '%MOTOR VEHICLE%' THEN 'Auto Parts'
    WHEN raw_industry ILIKE '%Motor Vehicle%' THEN 'Auto Parts'
    WHEN raw_industry ILIKE '%CARPET%RUG%' THEN 'Textiles'
    WHEN raw_industry ILIKE '%Carpet%Rug%' THEN 'Textiles'
    WHEN raw_industry ILIKE '%BROADWOVEN%' THEN 'Textiles'
    WHEN raw_industry ILIKE '%Women%Outerwear%' THEN 'Apparel'
    WHEN raw_industry ILIKE '%MEN%FURNISHG%' THEN 'Apparel'
    WHEN raw_industry ILIKE '%Men%Furnishg%' THEN 'Apparel'
    
    -- Consumer Staples
    WHEN raw_industry ILIKE '%GRAIN MILL%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%CANNED, FROZEN%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%Canned%Frozen%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%Canned Fruits%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%FOOD AND KINDRED%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%MISCELLANEOUS FOOD%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%Miscellaneous Food%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%FATS & OILS%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%MEAT PACKING%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%POULTRY%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%Poultry%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%SUGAR%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%SAUSAGE%' THEN 'Food Products'
    WHEN raw_industry ILIKE '%BOTTLED%' THEN 'Beverages'
    WHEN raw_industry ILIKE '%Bottled%Canned%' THEN 'Beverages'
    WHEN raw_industry ILIKE '%BEVERAGES%' THEN 'Beverages'
    WHEN raw_industry ILIKE '%Beverages%' THEN 'Beverages'
    WHEN raw_industry ILIKE '%MALT BEVERAGES%' THEN 'Beverages'
    WHEN raw_industry ILIKE '%Cigarettes%' THEN 'Tobacco'
    WHEN raw_industry ILIKE '%TOBACCO%' THEN 'Tobacco'
    WHEN raw_industry ILIKE '%Tobacco%' THEN 'Tobacco'
    WHEN raw_industry ILIKE '%WHOLESALE-GROCERIES%' THEN 'Food Distribution'
    WHEN raw_industry ILIKE '%RETAIL-GROCERY%' THEN 'Food Retail'
    WHEN raw_industry ILIKE '%Retail Grocery%' THEN 'Food Retail'
    WHEN raw_industry ILIKE '%RETAIL-FOOD%' THEN 'Food Retail'
    WHEN raw_industry ILIKE '%RETAIL-CONVENIENCE%' THEN 'Food Retail'
    
    -- Consumer Discretionary
    WHEN raw_industry ILIKE '%Automobiles%' THEN 'Automobiles'
    WHEN raw_industry ILIKE '%MOTORCYCLES%' THEN 'Automobiles'
    WHEN raw_industry ILIKE '%MOBILE HOME%' THEN 'Homebuilders'
    WHEN raw_industry ILIKE '%RETAIL-AUTO DEALER%' THEN 'Auto Dealers'
    WHEN raw_industry ILIKE '%Retail Auto Dealer%' THEN 'Auto Dealers'
    WHEN raw_industry ILIKE '%RETAIL-AUTO & HOME%' THEN 'Auto Parts Retail'
    WHEN raw_industry ILIKE '%RETAIL-EATING%' THEN 'Restaurants'
    WHEN raw_industry ILIKE '%Retail Eating%' THEN 'Restaurants'
    WHEN raw_industry ILIKE '%Restaurant%' THEN 'Restaurants'
    WHEN raw_industry ILIKE '%HOTELS%' THEN 'Hotels & Leisure'
    WHEN raw_industry ILIKE '%SERVICES-MISCELLANEOUS AMUSEMENT%' THEN 'Hotels & Leisure'
    WHEN raw_industry ILIKE '%Services Miscellaneous Amusement%' THEN 'Hotels & Leisure'
    WHEN raw_industry ILIKE '%SERVICES-AMUSEMENT%' THEN 'Hotels & Leisure'
    WHEN raw_industry ILIKE '%SERVICES-RACING%' THEN 'Hotels & Leisure'
    WHEN raw_industry ILIKE '%RETAIL-FAMILY CLOTHING%' THEN 'Apparel Retail'
    WHEN raw_industry ILIKE '%Retail Family Clothing%' THEN 'Apparel Retail'
    WHEN raw_industry ILIKE '%Apparel Retail%' THEN 'Apparel Retail'
    WHEN raw_industry ILIKE '%RETAIL-WOMEN%CLOTHING%' THEN 'Apparel Retail'
    WHEN raw_industry ILIKE '%RETAIL-SHOE%' THEN 'Apparel Retail'
    WHEN raw_industry ILIKE '%APPAREL%' THEN 'Apparel'
    WHEN raw_industry ILIKE '%FOOTWEAR%' THEN 'Apparel'
    WHEN raw_industry ILIKE '%RETAIL-CATALOG%' THEN 'E-Commerce'
    WHEN raw_industry ILIKE '%Retail Catalog%' THEN 'E-Commerce'
    WHEN raw_industry ILIKE '%Broadline Retail%' THEN 'E-Commerce'
    WHEN raw_industry ILIKE '%RETAIL-DEPARTMENT%' THEN 'Department Stores'
    WHEN raw_industry ILIKE '%Retail Department%' THEN 'Department Stores'
    WHEN raw_industry ILIKE '%RETAIL-VARIETY%' THEN 'Discount Stores'
    WHEN raw_industry ILIKE '%Retail Variety%' THEN 'Discount Stores'
    WHEN raw_industry ILIKE '%Discount Store%' THEN 'Discount Stores'
    WHEN raw_industry ILIKE '%RETAIL-LUMBER%' THEN 'Home Improvement'
    WHEN raw_industry ILIKE '%RETAIL-BUILDING MATERIAL%' THEN 'Home Improvement'
    WHEN raw_industry ILIKE '%Home Improvement%' THEN 'Home Improvement'
    WHEN raw_industry ILIKE '%RETAIL-FURNITURE%' THEN 'Home Furnishings'
    WHEN raw_industry ILIKE '%Retail Furniture%' THEN 'Home Furnishings'
    WHEN raw_industry ILIKE '%OFFICE FURNITURE%' THEN 'Home Furnishings'
    WHEN raw_industry ILIKE '%RETAIL-HOBBY%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%RETAIL-JEWELRY%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%Retail Jewelry%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%JEWELRY%SILVERWARE%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%RETAIL-MISCELLANEOUS%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%Retail Miscellaneous%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%RETAIL-RETAIL STORES%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%Retail Retail Stores%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%RETAIL-RADIO%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%RETAIL-NONSTORE RETAILER%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%WATCHES%CLOCK%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE '%SPORTING%' THEN 'Leisure Products'
    WHEN raw_industry ILIKE '%GAMES, TOYS%' THEN 'Leisure Products'
    WHEN raw_industry ILIKE '%Games%Toys%' THEN 'Leisure Products'
    WHEN raw_industry ILIKE '%DOLLS%STUFFED%' THEN 'Leisure Products'
    WHEN raw_industry ILIKE '%Dolls%Stuffed%' THEN 'Leisure Products'
    WHEN raw_industry ILIKE '%SERVICES-EDUCATIONAL%' THEN 'Education'
    WHEN raw_industry ILIKE '%Services Educational%' THEN 'Education'
    WHEN raw_industry ILIKE '%SERVICES-PERSONAL%' THEN 'Personal Services'
    WHEN raw_industry ILIKE '%Consumer Electronics%' THEN 'Consumer Electronics'
    
    -- Communication Services
    WHEN raw_industry ILIKE '%TELEPHONE COMMUNICATION%' THEN 'Telecom'
    WHEN raw_industry ILIKE '%Telecom%' THEN 'Telecom'
    WHEN raw_industry ILIKE '%TELEGRAPH%' THEN 'Telecom'
    WHEN raw_industry ILIKE '%RADIO BROADCASTING%' THEN 'Media'
    WHEN raw_industry ILIKE '%TELEVISION BROADCASTING%' THEN 'Media'
    WHEN raw_industry ILIKE '%NEWSPAPERS%PUBLISHING%' THEN 'Media'
    WHEN raw_industry ILIKE '%Miscellaneous Publishing%' THEN 'Media'
    WHEN raw_industry ILIKE '%SERVICES-MOTION PICTURE%' THEN 'Entertainment'
    WHEN raw_industry ILIKE '%Services Motion Picture%' THEN 'Entertainment'
    WHEN raw_industry ILIKE '%SERVICES-VIDEO TAPE%' THEN 'Entertainment'
    WHEN raw_industry ILIKE '%Entertainment%' THEN 'Entertainment'
    WHEN raw_industry ILIKE '%CABLE%PAY TELEVISION%' THEN 'Cable & Streaming'
    WHEN raw_industry ILIKE '%Cable%Pay Television%' THEN 'Cable & Streaming'
    WHEN raw_industry ILIKE '%COMMUNICATIONS SERVICES%' THEN 'Interactive Media'
    WHEN raw_industry ILIKE '%Communications Services%' THEN 'Interactive Media'
    WHEN raw_industry ILIKE '%Internet Content%' THEN 'Interactive Media'
    WHEN raw_industry ILIKE '%SERVICES-COMPUTER PROGRAMMING%' AND raw_industry ILIKE '%DATA PROC%' THEN 'Interactive Media'
    WHEN raw_industry ILIKE '%Services Computer Programming Data%' THEN 'Interactive Media'
    
    -- Utilities
    WHEN raw_industry ILIKE '%ELECTRIC SERVICE%' THEN 'Electric Utilities'
    WHEN raw_industry ILIKE '%ELECTRIC%OTHER SERVICE%COMBINED%' THEN 'Electric Utilities'
    WHEN raw_industry ILIKE '%Electric Other Services%' THEN 'Electric Utilities'
    WHEN raw_industry ILIKE '%Utilities - Regulated Electric%' THEN 'Electric Utilities'
    WHEN raw_industry ILIKE '%COGENERATION%' THEN 'Independent Power'
    WHEN raw_industry ILIKE '%Independent Power%' THEN 'Independent Power'
    WHEN raw_industry ILIKE '%GAS%OTHER SERVICES%COMBINED%' THEN 'Gas Utilities'
    WHEN raw_industry ILIKE '%Gas Other Services%' THEN 'Gas Utilities'
    WHEN raw_industry ILIKE '%WATER SUPPLY%' THEN 'Water Utilities'
    WHEN raw_industry ILIKE '%Utilities%' THEN 'Utilities - Diversified'
    
    -- Real Estate
    WHEN raw_industry ILIKE '%REAL ESTATE%' THEN 'REITs'
    WHEN raw_industry ILIKE '%REIT%' THEN 'REITs'
    WHEN raw_industry ILIKE '%LESSORS OF REAL PROPERTY%' THEN 'REITs'
    WHEN raw_industry ILIKE '%OPERATOR%APARTMENT%' THEN 'REITs'
    WHEN raw_industry ILIKE '%Operator%Apartment%' THEN 'REITs'
    WHEN raw_industry ILIKE '%OPERATOR%NONRESIDENTIAL%' THEN 'REITs'
    WHEN raw_industry ILIKE '%Operator%Nonresidential%' THEN 'REITs'
    WHEN raw_industry ILIKE '%LAND SUBDIVID%' THEN 'Real Estate Development'
    WHEN raw_industry ILIKE '%OPERATIVE BUILDER%' THEN 'Homebuilders'
    
    -- Wholesale/Distribution catchall
    WHEN raw_industry ILIKE '%WHOLESALE-%' THEN 'Distribution'
    WHEN raw_industry ILIKE '%Wholesale%' THEN 'Distribution'
    
    -- Services catchalls
    WHEN raw_industry ILIKE '%SERVICES-ADVERTISING%' THEN 'Advertising'
    WHEN raw_industry ILIKE '%Advertising%' THEN 'Advertising'
    WHEN raw_industry ILIKE '%SERVICES-DETECTIVE%' THEN 'Security Services'
    WHEN raw_industry ILIKE '%Security Software%' THEN 'Cybersecurity'
    WHEN raw_industry ILIKE '%SERVICES-PREPACKAGED SOFTWARE%' THEN 'Software'
    WHEN raw_industry ILIKE '%SERVICES-COMPUTER%' THEN 'IT Services'
    WHEN raw_industry ILIKE '%Services Computer%' THEN 'IT Services'
    WHEN raw_industry ILIKE '%Services Commercial Physical%' THEN 'Research Services'
    WHEN raw_industry ILIKE '%SERVICES-COMMERCIAL PHYSICAL%' THEN 'Research Services'
    WHEN raw_industry ILIKE '%SERVICES-BUSINESS%' THEN 'Business Services'
    WHEN raw_industry ILIKE '%Services Business%' THEN 'Business Services'
    WHEN raw_industry ILIKE '%Services Services%' THEN 'Business Services'
    WHEN raw_industry ILIKE '%SERVICES-%' THEN 'Business Services'
    
    -- Manufacturing catchalls
    WHEN raw_industry ILIKE '%MISCELLANEOUS MANUFACTURING%' THEN 'Diversified Manufacturing'
    WHEN raw_industry ILIKE '%COATING, ENGRAVING%' THEN 'Diversified Manufacturing'
    WHEN raw_industry ILIKE '%COMMERCIAL PRINTING%' THEN 'Diversified Manufacturing'
    WHEN raw_industry ILIKE '%Commercial Printing%' THEN 'Diversified Manufacturing'
    WHEN raw_industry ILIKE '%BLANKBOOK%' THEN 'Diversified Manufacturing'
    WHEN raw_industry ILIKE '%MANIFOLD BUSINESS%' THEN 'Diversified Manufacturing'
    
    -- Remaining retail catchall
    WHEN raw_industry ILIKE 'Retail%' THEN 'Specialty Retail'
    WHEN raw_industry ILIKE 'RETAIL-%' THEN 'Specialty Retail'
    
    -- Fallback
    ELSE COALESCE(raw_industry, 'Other')
  END;
$function$;
